name: Compare Excel Files

on:
  push: 
    paths:
      - '**/*.xlsx'


jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Compare Excel files
        run: |
          git diff --name-only HEAD^ HEAD | grep '.xlsx' | while read file; do
          # Save the new version
          cp "$file" ".github/data/newfile1.xlsx"

          # Save the old version from the previous commit
          git checkout HEAD^ -- "$file"
          cp "$file" ".github/data/oldfile1.xlsx"

          # Run the comparison
          python compare_excel.py

          # Restore the new version (optional)
          git checkout HEAD -- "$file"
          done

