name: Compare Excel Files by Date

on:
  push:
    paths:
      - 'excel_files/**/*.xlsx'
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl tabulate
         
      - name: Run Excel comparison
        run: python Excell_Compare1.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: diff-report
          path: highlighted_all_sheets.xlsx
      
